export const universities = [
    { name: "PU", src: "/Universities/PU.svg", width: 216, height: 76 },
    { name: "NUST", src: "/Universities/NUST.svg", width: 195, height: 76 },
    { name: "FAST", src: "/Universities/FAST.svg", width: 268, height: 76 },
    {
      name: "COMSATS",
      src: "/Universities/COMASTS.svg",
      width: 218,
      height: 74,
    },
    { name: "LUMS", src: "/Universities/LUMS.svg", width: 204, height: 65 },
    { name: "AIR", src: "/Universities/AIR.svg", width: 74, height: 65 },
    { name: "GIKI", src: "/Universities/GIKI.svg", width: 216, height: 74 },
    { name: "PIEAS", src: "/Universities/PIEAS.svg", width: 246, height: 74 },
    { name: "UCP", src: "/Universities/UCP.svg", width: 276, height: 74 },
    { name: "UMT", src: "/Universities/UMT.svg", width: 163, height: 74 },
    { name: "UOL", src: "/Universities/UOL.svg", width: 203, height: 74 },
    { name: "KC", src: "/Universities/KC.svg", width: 177, height: 75 },
    { name: "GCU", src: "/Universities/GCU.svg", width: 98, height: 75 },
  ];